baseurl = "https://endormi.io/"
title = "Endormi"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20
pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Erno Salo"
    info = "Software Developer at Foredata Oy"
    description = "Endormi's personal website"
    keywords = "developer,personal,website,portfolio"
    avatarurl = "images/avi.png"
    favicon_32 = "images/avi.png"
    favicon_16 = "images/avi.png"
    hideCredits = true
    colorScheme = "auto"
    hideColorSchemeToggle = false
    rtl = false
    custom_css = ["/css/custom.css"]

[params.csp]
    childsrc = ["'self'"]
    fontsrc = ["'self'", "https://fonts.gstatic.com"]
    formaction = ["'self'"]
    framesrc = ["'self'"]
    imgsrc = ["'self'"]
    objectsrc = ["'none'"]
    stylesrc = ["'self'", "'unsafe-inline'"]
    scriptsrc = ["'self'", "'unsafe-inline'"]

[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/endormi/"

[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    weight = 2
    url = "https://linkedin.com/in/ernosalo/"

[[params.social]]
    name = "Dev.to"
    icon = "fa fa-dev-to fa-2x"
    weight = 3
    url = "https://dev.to/endormi/"

[[params.social]]
    name = "Source Code"
    icon = "fa fa-file-code-o fa-2x"
    weight = 4
    url = "https://github.com/endormi/www"

[[params.social]]
    name = "Discord"
    icon = "fa fa-discord fa-2x"
    weight = 5
    url = "https://discord.gg/MSTQKRE"

[languages]
    [languages.en]
        languagename = "EN"

            [languages.en.menu]

                [[languages.en.menu.main]]
                    name = "Home"
                    weight = 1
                    url = "/"

                [[languages.en.menu.main]]
                    name = "About"
                    weight = 2
                    url = "/about/"

                [[languages.en.menu.main]]
                    name = "Open Source"
                    weight = 3
                    url = "/open-source/"

                [[languages.en.menu.main]]
                    name = "Posts"
                    weight = 4
                    url = "https://dev.to/endormi"

                [[languages.en.menu.main]]
                    name = "Uses"
                    weight = 5
                    url = "/uses/"

                [[languages.en.menu.main]]
                    name = "Thanks"
                    weight = 6
                    url = "/thanks/"

    [languages.fr]
        languagename = "FR"

        [languages.fr.params]
            author = "Erno Salo"
            info = "Développeur logiciel à Foredata Oy"
            description = "Le site personnel de Endormi"
            keywords = "développeur,personnel,site,portefeuille"

                [languages.fr.menu]

                    [[languages.fr.menu.main]]
                        name = "Accueil"
                        weight = 1
                        url = "/"

                    [[languages.fr.menu.main]]
                        name = "À propos"
                        weight = 2
                        url = "/à-propos/"

                    [[languages.fr.menu.main]]
                        name = "Open Source"
                        weight = 3
                        url = "/open-source/"

                    [[languages.fr.menu.main]]
                        name = "Des postes"
                        weight = 4
                        url = "https://dev.to/endormi"

                    [[languages.fr.menu.main]]
                        name = "Les usages"
                        weight = 5
                        url = "/les-usages/"

                    [[languages.fr.menu.main]]
                        name = "Merci"
                        weight = 6
                        url = "/merci/"
