baseurl = "https://endormi.io/"

title = "Endormi"

theme = "hugo-coder"

languagecode = "en"

defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"

pygmentscodefences = true

pygmentscodefencesguesssyntax = true

[params]
    author = "Erno Salo"

    info = "Full Stack Developer at Foredata Oy"

    description = "Endormi's personal website"

    keywords = "developer,personal,website"

    avatarurl = "images/avi.png"

    favicon_32 = "images/avi.png"

    favicon_16 = "images/avi.png"

    footercontent = "Â© 2019 Endormi"

    hidecredits = true

    hidecopyright = true

    rtl = false

    custom_css = ["/css/custom.css"]

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/endormi/"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://linkedin.com/in/ernosalo/"

[[params.social]]
    name = "Dev.to"
    icon = "fab fa-dev fa-2x"
    weight = 3
    url = "https://dev.to/endormi/"

[[params.social]]
    name = "NPM"
    icon = "fab fa-npm fa-2x"
    weight = 4
    url = "https://www.npmjs.com/~endormi"

[[params.social]]
    name = "Gmail"
    icon = "fas fa-envelope fa-2x"
    weight = 5
    url = "mailto:contactendormi@gmail.com"

[[menu.main]]
    name = "Home"
    weight = 1
    url = "/"

[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"

[[menu.main]]
    name = "Open Source"
    weight = 3
    url = "/open-source/"

[[menu.main]]
    name = "Uses"
    weight = 4
    url = "/uses/"

[[menu.main]]
    name = "Contact"
    weight = 5
    url  = "mailto:contactendormi@gmail.com"
