[build]
  publish = "public"
  command = "make prepare && hugo --source --baseURL $URL"

[context.production.environment]
  HUGO_VERSION = "0.54.0"

[context.deploy-preview]
  command = "make prepare && hugo --source --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.54.0"